version: '3'

services:

    php:
        container_name: todo_list_laravel_api_container
        build: './docker/php'
        ports:
            - '5173:5173'
        volumes:
            - '.:/var/www/html'
        networks:
            - 'todo-net'
        depends_on:
            - pgsql

    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - 'todo-net'
        depends_on:
            - php

    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'todo-net-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - 'todo-net'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s


networks:
    todo-net:
        driver: bridge
volumes:
    todo-net-pgsql:
        driver: local
